language: python

python:
  - "nightly"
  - "3.8"
  - "3.7"
  - "3.6"
  # - "3.9"
  # 3.9 doesn't exist yet.

install:
  - pip install pytest-asyncio
  - pip install -r requirements.txt
script:
  - pytest tests/ -vvv
cache: pip
matrix:
    allow_failures:
        - python: "nightly"
        - python: "3.7"
        - python: "3.6"
notifications:
  email:
    recipients:
      - bryan.hu.cn@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
