language: python

python:
  - "3.8"
  # - "3.9"
  # 3.9 doesn't exist yet.

install: #  Unnessecary
  - pip install pytest-asyncio
#   - pip install -r requirements.txt
#   - pytest-asyncio
script:
  - pytest tests/ -vvv
cache: pip
notifications:
  email:
    recipients:
      - bryan.hu.cn@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
