language: python

python:
  - "3.8"

install:
  - python3 -m pip install pytest
  - python3 -m pip install -r requirements.txt
script:
  - pytest
notifications:
  email:
    recipients:
      - bryan.hu.cn@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
