language: python

python:
  - "3.8"
  - "3.9"

install:
  - pip install pytest
  - pip install -r requirements.txt
script:
  - pytest
cache: pip
notifications:
  email:
    recipients:
      - bryan.hu.cn@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
